### ISSUE TITLE
fix all bugs (fixbugs)

### ISSUE THREAD

**Issue by jsdevprocess** [jsdevprocess/org_testrepo#1]
please fix all bugs in js8 and jscockpit repos

# Tasks

- [ ] fixbugs: bug created in code_js8 repo #[1](https://github.com/jsdevprocess/code_js8/issues/1)
- [ ] fixbugs: portal doesnt start #[2](https://github.com/jsdevprocess/org_testrepo/issues/2)
- [ ] fixbugs: api server syntax error #[3](https://github.com/jsdevprocess/org_testrepo/issues/3)

# Remaining Time: 0h

![Progress](http://progressed.io/bar/0)

# Waffle: [kanban](https://waffle.io/gig-projects/org_development?search=fixbugs:&label=type_task)
